version: "3.9"
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama

  app:
    build: .
    depends_on:
      - ollama
    volumes:
      - ./app:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434
    stdin_open: true
    tty: true

volumes:
  ollama_models:
