[theme]
base="light"
primaryColor="#4CAF50"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F5F5F5"
textColor="#000000"
font="sans serif"

[server]
headless=true
enableCORS=false
enableXsrfProtection=false

[client]
toolbarMode="minimal"
showSidebarNavigation=true
